{% set name = "forestplot" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffba9fe7781d8cddd468ff63942e751786a312bc810d6fa0ff311187f577b9c0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - forestplot

about:
  home: https://github.com/lsys/forestplot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to make publication-ready but customizable coefficient plots.
  doc_url: https://forestplot.rtfd.io/
  dev_url: https://github.com/lsys/forestplot

extra:
  recipe-maintainers:
    - lsys
